Add MariaDB databases
ude-soco/elas-official pull request #170
Opened 2023-11-08 16:40 UTC by shoebjoarder

Probably we need to install the python3 and MySQL development headers and libraries using: `sudo apt-get install python3-dev default-libmysqlclient-dev build-essential`

2023-11-08 17:20 UTC, ralf-berger requested changes
Not ready:
* does not build
* Kubernetes config missing

2023-11-08 19:37 UTC, closed without merging

2023-11-08 21:32 UTC, shoebjoarder commented
Ah, didn't notice that you created a branch!

2023-11-09 13:25 UTC, ralf-berger commented on backend/3-auth/Pipfile.lock
Breaks build for me, `jellyfish-1.0.1` fails with `Checking for Rust toolchain....`

2023-11-09 13:26 UTC, ralf-berger commented on backend/4-e3selector/Pipfile.lock
Breaks build for me, `jellyfish-1.0.1` fails with `Checking for Rust toolchain....`

2023-11-09 14:35 UTC, shoebjoarder commented on backend/4-e3selector/Pipfile.lock
For me the build was successful when `default-libmysqlclient-dev` added to Dockerfile.

```Dockerfile
ENV BUILD_DEPS "build-essential pkg-config libpq-dev default-libmysqlclient-dev"
```

2023-11-09 14:39 UTC, shoebjoarder commented on backend/3-auth/Pipfile.lock
For me the build was successful when `default-libmysqlclient-dev` added to Dockerfile.

```Dockerfile
ENV BUILD_DEPS "build-essential pkg-config libpq-dev default-libmysqlclient-dev"
```

2023-11-09 14:45 UTC, shoebjoarder commented on backend/4-e3selector/Pipfile.lock
Same, added `default-libmysqlclient-dev` to successfully build it.

```Dockerfile
ENV BUILD_DEPS "build-essential pkg-config libpq-dev default-libmysqlclient-dev"
```

2023-11-17 09:19 UTC, ralf-berger commented on backend/3-auth/Pipfile.lock
x86 emulation seems to works